const ADD_PRODUCT = 'ADD_PRODUCT'
const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
const CHANGE_PRODUCT_QUANTITY = ' CHANGE_PRODUCT_QUANTITY'

export default {
    ADD_PRODUCT,
    REMOVE_PRODUCT,
    CHANGE_PRODUCT_QUANTITY
}