const SET_PRODUCTS = 'SET_PRODUCTS'
const SET_TYPE = 'SET_TYPE'
const SET_PRODUCTS_VISIBILITY = 'SET_PRODUCT_VISIBILITY'

export default {
    SET_PRODUCTS,
    SET_TYPE,
    SET_PRODUCTS_VISIBILITY
}