Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/584/291584/ShotType1_225x225.jpg', product_type: "meats", description: 'Schab wieprzowy bez kości', price: 9.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/333/291333/ShotType1_225x225.jpg', product_type: "meats", description: 'Żeberka wieprzowe ekstra mięsne', price: 15.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/600/293600/ShotType1_225x225.jpg', product_type: "meats", description: 'Karkówka wieprzowa bez kości', price: 17.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/035/297035/ShotType1_225x225.jpg', product_type: "meats", description: 'Łopatka wieprzowa bez kości', price: 15.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/432/298432/ShotType1_225x225.jpg', product_type: "meats", description: 'Szynka wieprzowa bez kości', price: 17.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/512/290512/ShotType1_225x225.jpg', product_type: "meats", description: 'Golonka wieprzowa przednia', price: 9.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/262/297262/ShotType1_225x225.jpg', product_type: "meats", description: 'Łopatka wołowa bez kości', price: 26.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/272/297272/ShotType1_225x225.jpg', product_type: "meats", description: 'Łigawa wołowa bez kości', price: 25.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/445/298445/ShotType1_225x225.jpg', product_type: "meats", description: 'Mięso wołowe na bitki', price: 25.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/267/297267/ShotType1_225x225.jpg', product_type: "meats", description: 'Szponder wołowy z kością', price: 19.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/413/290413/ShotType1_225x225.jpg', product_type: "meats", description: 'Filet z kurczaka"', price: 16.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/898/291898/ShotType1_225x225.jpg', product_type: "meats", description: 'Ćwiartka z kurczaka', price: 5.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/391/290391/ShotType1_225x225.jpg', product_type: "meats", description: 'Filet z indyka', price: 14.99, key_word: '', quantity_available: 50)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/418/290418/ShotType1_225x225.jpg', product_type: "meats", description: 'Podudzie z kurczaka', price: 7.99, key_word: '', quantity_available: 50)

Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/197/290197/ShotType1_225x225.jpg', product_type: "fishes", description: 'Makrela wędzona', price: 15.90, key_word: '', quantity_available: 25)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/254/290254/ShotType1_225x225.jpg', product_type: "fishes", description: 'Brzuszki z łososia wędzone', price: 19.90, key_word: '', quantity_available: 25)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/092/292092/ShotType1_225x225.jpg', product_type: "fishes", description: 'Szprot wędzony', price: 11.90, key_word: '', quantity_available: 25)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/145/293145/ShotType1_225x225.jpg', product_type: "fishes", description: 'Pikling wędzony', price: 10.90, key_word: '', quantity_available: 25)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/068/296068/ShotType1_225x225.jpg', product_type: "fishes", description: 'Śledź solony', price: 12.90, key_word: '', quantity_available: 25)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/061/296061/ShotType1_225.jpg', product_type: "fishes", description: 'Dorsz atlantycki', price: 16.90, key_word: '', quantity_available: 25)

Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/867/0000020205867/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Banan', price: 4.90, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/127/5903034455127/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Limonka', price: 3.49, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/869/295869/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Ananas', price: 4.95, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/978/5051007103978/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Awokado Hass', price: 5.79, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/547/5906881465547/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Kiwi', price: 13.58, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/664/290664/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Pomidory luz', price: 4.99, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/267/0000025611267/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Ogórek długi', price: 1.99, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/699/290699/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Papryka czerwona', price: 7.99, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/416/5905133520416/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Marchew', price: 3.99, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/985/0000029520985/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Pietruszka korzeń', price: 4.99, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/666/290666/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Buraki', price: 2.49, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/150/294150/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Bataty', price: 9.99, key_word: '', quantity_available: 55)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/558/296558/ShotType1_225x225.jpg', product_type: "fruits_and_vegetables", description: 'Ziemniaki luz', price: 2.99, key_word: '', quantity_available: 55)

Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/335/5900512320335/ShotType1_225x225.jpg', product_type: "dairy", description: 'Mlekovita wypasione mleko UHT 2,0% 1L', price: 2.79, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/042/5900820000042/ShotType1_225x225.jpg', product_type: "dairy", description: 'Łaciate mleko UHT 2% 1L', price: 2.79, key_word: '')
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/359/5900512320359/ShotType1_225x225.jpg', product_type: "dairy", description: 'Mlekovita wypasione mleko UHT 3,2% 1L', price: 2.89, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/028/5900820000028/ShotType1_225x225.jpg', product_type: "dairy", description: 'Łaciate mleko UHT 0,5% 1L', price: 2.79, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/515/5906040063515/ShotType1_225x225.jpg', product_type: "dairy", description: 'Primo jogurt naturalny 200g', price: 7.72, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/034/5900197000034/ShotType1_225x225.jpg', product_type: "dairy", description: 'Bakoma jogurt naturalny gęsty', price: 8.60, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/480/5900643032480/ShotType1_225x225.jpg', product_type: "dairy", description: 'Activia jogurt naturalny 180g', price: 8.44, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/368/5900643019368/ShotType1_225x225.jpg', product_type: "dairy", description: 'Danone jogurt naturalny łagodny 165g', price: 8.73, key_word: '', quantity_available: 30)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/161/5905058000161/ShotType1_225x225.jpg', product_type: "dairy", description: 'Jogurt naturalny kremowy 200g', price: 4.60, key_word: '', quantity_available: 30)

Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/928/5051007111928/ShotType1_225x225.jpg', product_type: "frozens", description: 'Brokuły 450g', price: 7.67, key_word: '', quantity_available: 20)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/730/5900477000730/ShotType1_225x225.jpg', product_type: "frozens", description: 'Szpinak rozdrobniony 450g', price: 9.76, key_word: '', quantity_available: 20)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/207/5051007122207/ShotType1_225x225.jpg', product_type: "frozens", description: 'Kalafior 450g', price: 7.67, key_word: '', quantity_available: 20)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/000/5051007112000/ShotType1_225x225.jpg', product_type: "frozens", description: 'Mieszanka warzywna z ziemniakami', price: 7.67, key_word: '', quantity_available: 20)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/108/5051007122108/ShotType1_225x225.jpg', product_type: "frozens", description: 'Fasolka szparagowa 450g', price: 5.67, key_word: '', quantity_available: 20)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/761/5900477000761/ShotType1_225x225.jpg', product_type: "frozens", description: 'Marchewka z groszkiem 450g', price: 5.67, key_word: '', quantity_available: 20)

Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/767/8711000513767/ShotType1_90x90.jpg', product_type: "coffes", description: 'Jacobs Cronat Gold kawa rozpuszczalna 200g', price: 39.99, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/220/7613032734220/ShotType1_90x90.jpg', product_type: "coffes", description: 'Nescafe Creme kawa rozpuszczalna 200g', price: 34.99, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/045/8711000521045/ShotType1_90x90.jpg', product_type: "coffes", description: 'Jacobs Kronung kawa rozpuszczalna 200g', price: 38.50, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/722/8711000525722/ShotType1_90x90.jpg', product_type: "coffes", description: 'Jacobs Kronung kawa mielona 200g', price: 27.99, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/881/7613031918881/ShotType1_90x90.jpg', product_type: "coffes", description: 'Nescafe classic kawa rozpuszczalna 200g', price: 29.99, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/826/8711000517826/ShotType1_90x90.jpg', product_type: "coffes", description: 'Jacobs Velvet kawa rozpuszczalna 200g', price: 22.50, key_word: '', quantity_available: 35)

Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/030/5901588016030/ShotType1_225x225.jpg', product_type: "sweets", description: 'Wedel czekolada gorzka klasyczna 64%', price: 4.99, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/610/5900102312610/ShotType1_225x225.jpg', product_type: "sweets", description: 'Wawel czekolada gorzka klasyczna 70%', price: 4.50, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/701/0000040084701/ShotType1_225x225.jpg', product_type: "sweets", description: 'Kinder chocolate batoniki z mlecznej czkolady', price: 3.49, key_word: '', quantity_available: 35)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/502/3045140105502/ShotType1_225x225.jpg', product_type: "sweets", description: 'Milka czekolada mleczna', price: 5.20, key_word: '')
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/419/8584004041419/ShotType1_225x225.jpg', product_type: "sweets", description: 'Góralki', price: 2.30, key_word: '', quantity_available: 15)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/396/0000059042396/ShotType1_225x225.jpg', product_type: "sweets", description: 'Wedel WW', price: 2.30, key_word: '', quantity_available: 15)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/100/7622210416100/ShotType1_225x225.jpg', product_type: "sweets", description: '3Bit', price: 2.00, key_word: '', quantity_available: 15)
Product.create(source: 'https://secure.ce-tescoassets.com/assets/PL/761/0000080761761/ShotType1_225x225.jpg', product_type: "sweets", description: 'Kinder Bueno', price: 5.50, key_word: '', quantity_available: 15)

dolnośląskie = Province.create(name: 'Dolnośląskie')
kujawsko_pomorskie = Province.create(name: 'Kujawsko-pomorskie')
lubelskie = Province.create(name: 'Lubelskie')
lubuskie = Province.create(name: 'Lubuskie')
lodzkie = Province.create(name: 'Łódzkie')
malopolskie = Province.create(name: 'Małopolskie')
mazowieckie = Province.create(name: 'Mazowieckie')
opolskie = Province.create(name: 'Opolskie')
podkarpackie = Province.create(name: 'Podkarpackie')
podlaskie = Province.create(name: 'Podlaskie')
pomorskie = Province.create(name: 'Pomorskie')
slaskie = Province.create(name: 'Śląskie')
swietokrzyskie = Province.create(name: 'Świętokrzyskie')
warminsko_mazurskie = Province.create(name: 'Warmińsko-mazurskie')
wielkopolskie = Province.create(name: 'Wielkopolskie')
zachodniopomorskie = Province.create(name: 'Zachodniopomorskie')

City.create(name: 'Wrocław', province_id: dolnośląskie.id)
City.create(name: 'Wałbrzych', province_id: dolnośląskie.id)
City.create(name: 'Legnica', province_id: dolnośląskie.id)
City.create(name: 'Jelenia Góra', province_id: dolnośląskie.id)
City.create(name: 'Lubin', province_id: dolnośląskie.id)
City.create(name: 'Głogów', province_id: dolnośląskie.id)
City.create(name: 'Bolesławiec', province_id: dolnośląskie.id)
City.create(name: 'Oława', province_id: dolnośląskie.id)

City.create(name: 'Bydgoszcz', province_id: kujawsko_pomorskie.id)
City.create(name: 'Toruń', province_id: kujawsko_pomorskie.id)
City.create(name: 'Włocławek', province_id: kujawsko_pomorskie.id)
City.create(name: 'Grudziądz', province_id: kujawsko_pomorskie.id)
City.create(name: 'Inowrocław', province_id: kujawsko_pomorskie.id)
City.create(name: 'Brodnica', province_id: kujawsko_pomorskie.id)
City.create(name: 'Tuchola', province_id: kujawsko_pomorskie.id)
City.create(name: 'Świecie', province_id: kujawsko_pomorskie.id)

City.create(name: 'Biała Podlaska', province_id: lubelskie.id)
City.create(name: 'Chełm', province_id: lubelskie.id)
City.create(name: 'Lublin', province_id: lubelskie.id)
City.create(name: 'Zamość', province_id: lubelskie.id)
City.create(name: 'Puławy', province_id: lubelskie.id)
City.create(name: 'Świdwik', province_id: lubelskie.id)
City.create(name: 'Lubartów', province_id: lubelskie.id)
City.create(name: 'Dęblin', province_id: lubelskie.id)

City.create(name: 'Babimost', province_id: lubuskie.id)
City.create(name: 'Cybinka', province_id: lubuskie.id)
City.create(name: 'Gorzów Wlkp.', province_id: lubuskie.id)
City.create(name: 'Gubin', province_id: lubuskie.id)
City.create(name: 'Iłowa', province_id: lubuskie.id)
City.create(name: 'Jasień', province_id: lubuskie.id)
City.create(name: 'Kargowa', province_id: lubuskie.id)
City.create(name: 'Nowa sól', province_id: lubuskie.id)
City.create(name: 'Słubice', province_id: lubuskie.id)

City.create(name: 'Łódź', province_id: lodzkie.id)
City.create(name: 'Piotrków Trybunalski', province_id: lodzkie.id)
City.create(name: 'Pabianice', province_id: lodzkie.id)
City.create(name: 'Zgierz', province_id: lodzkie.id)
City.create(name: 'Konstantynów Łódźki', province_id: lodzkie.id)
City.create(name: 'Brzeziny', province_id: lodzkie.id)
City.create(name: 'Skierniewice', province_id: lodzkie.id)
City.create(name: 'Bełchatów', province_id: lodzkie.id)
City.create(name: 'Sieradz', province_id: lodzkie.id)
City.create(name: 'Łowicz', province_id: lodzkie.id)

City.create(name: 'Kraków', province_id: malopolskie.id)
City.create(name: 'Bochnia', province_id: malopolskie.id)
City.create(name: 'Brzesko', province_id: malopolskie.id)
City.create(name: 'Chrzanów', province_id: malopolskie.id)
City.create(name: 'Dąbrowa Tarnowska', province_id: malopolskie.id)
City.create(name: 'Gorlice', province_id: malopolskie.id)
City.create(name: 'Limanowa', province_id: malopolskie.id)
City.create(name: 'Wadowice', province_id: malopolskie.id)

City.create(name: 'Warszawa', province_id: mazowieckie.id)
City.create(name: 'Radom', province_id: mazowieckie.id)
City.create(name: 'Płock', province_id: mazowieckie.id)
City.create(name: 'Siedlce', province_id: mazowieckie.id)
City.create(name: 'Pruszków', province_id: mazowieckie.id)
City.create(name: 'Legionowo', province_id: mazowieckie.id)
City.create(name: 'Ostrołęka', province_id: mazowieckie.id)
City.create(name: 'Piaseczno', province_id: mazowieckie.id)

City.create(name: 'Opole', province_id: opolskie.id)
City.create(name: 'Gogolin', province_id: opolskie.id)
City.create(name: 'Krapkowice', province_id: opolskie.id)
City.create(name: 'Pruszków', province_id: opolskie.id)
City.create(name: 'Strzelce Opolskie', province_id: opolskie.id)
City.create(name: 'Kędzierzyn Koźle', province_id: opolskie.id)
City.create(name: 'Głogówek', province_id: opolskie.id)
City.create(name: 'Nysa', province_id: opolskie.id)

City.create(name: 'Rzeszów', province_id: podkarpackie.id)
City.create(name: 'Przemyśl', province_id: podkarpackie.id)
City.create(name: 'Krosno', province_id: podkarpackie.id)
City.create(name: 'Jarosław', province_id: podkarpackie.id)
City.create(name: 'Jaslo', province_id: podkarpackie.id)
City.create(name: 'Tarnobrzeg', province_id: podkarpackie.id)
City.create(name: 'Dębica', province_id: podkarpackie.id)
City.create(name: 'Mielec', province_id: podkarpackie.id)
City.create(name: 'Stalowa Wola', province_id: podkarpackie.id)
City.create(name: 'Sanok', province_id: podkarpackie.id)

City.create(name: 'Białystok', province_id: podlaskie.id)
City.create(name: 'Suwałki', province_id: podlaskie.id)
City.create(name: 'Łomza', province_id: podlaskie.id)
City.create(name: 'Augustów', province_id: podlaskie.id)
City.create(name: 'Ciechanowiec', province_id: podlaskie.id)
City.create(name: 'Brańsk', province_id: podlaskie.id)
City.create(name: 'Czyzew', province_id: podlaskie.id)
City.create(name: 'Lipsk', province_id: podlaskie.id)

City.create(name: 'Bytów', province_id: pomorskie.id)
City.create(name: 'Czarna Woda', province_id: pomorskie.id)
City.create(name: 'Człuchów', province_id: pomorskie.id)
City.create(name: 'Gdańsk', province_id: pomorskie.id)
City.create(name: 'Gdynia', province_id: pomorskie.id)
City.create(name: 'Krynica Morska', province_id: pomorskie.id)
City.create(name: 'Kwidzyń', province_id: pomorskie.id)
City.create(name: 'Lębork', province_id: pomorskie.id)

City.create(name: 'Gliwice', province_id: slaskie.id)
City.create(name: 'Katowice', province_id: slaskie.id)
City.create(name: 'Bytom', province_id: slaskie.id)
City.create(name: 'Bielsko-Biała', province_id: slaskie.id)
City.create(name: 'Ruda Śląska', province_id: slaskie.id)
City.create(name: 'Zabrze', province_id: slaskie.id)
City.create(name: 'Sosnowiec', province_id: slaskie.id)
City.create(name: 'Żywiec', province_id: slaskie.id)
City.create(name: 'Mysłowice', province_id: slaskie.id)
City.create(name: 'Tarnowskie Góry', province_id: slaskie.id)

City.create(name: 'Kielce', province_id: swietokrzyskie.id)
City.create(name: 'Ostrowiec Świętokrzyski', province_id: swietokrzyskie.id)
City.create(name: 'Starachowice', province_id: swietokrzyskie.id)
City.create(name: 'Sandomierz', province_id: swietokrzyskie.id)
City.create(name: 'Jędrzejów', province_id: swietokrzyskie.id)
City.create(name: 'Końskie', province_id: swietokrzyskie.id)

City.create(name: 'Olsztyn', province_id: warminsko_mazurskie.id)
City.create(name: 'Elbląg', province_id: warminsko_mazurskie.id)
City.create(name: 'Ełk', province_id: warminsko_mazurskie.id)
City.create(name: 'Iława', province_id: warminsko_mazurskie.id)
City.create(name: 'Ostróda', province_id: warminsko_mazurskie.id)
City.create(name: 'Gizycko', province_id: warminsko_mazurskie.id)
City.create(name: 'Mrągowo', province_id: warminsko_mazurskie.id)
City.create(name: 'Działdowo', province_id: warminsko_mazurskie.id)

City.create(name: 'Poznań', province_id: wielkopolskie.id)
City.create(name: 'Kalisz', province_id: wielkopolskie.id)
City.create(name: 'Konin', province_id: wielkopolskie.id)
City.create(name: 'Piła', province_id: wielkopolskie.id)
City.create(name: 'Ostrów Wielkopolski', province_id: wielkopolskie.id)
City.create(name: 'Gniezno', province_id: wielkopolskie.id)
City.create(name: 'Luboń', province_id: wielkopolskie.id)

City.create(name: 'Koszalin', province_id: zachodniopomorskie.id)
City.create(name: 'Białogard', province_id: zachodniopomorskie.id)
City.create(name: 'Choszczno', province_id: zachodniopomorskie.id)
City.create(name: 'Drawsko Pomorskie', province_id: zachodniopomorskie.id)
City.create(name: 'Goleniów', province_id: zachodniopomorskie.id)
City.create(name: 'Gryfice', province_id: zachodniopomorskie.id)
City.create(name: 'Gryfino', province_id: zachodniopomorskie.id)
City.create(name: 'Kamień Pomorski', province_id: zachodniopomorskie.id)









